#!/bin/bash
for i in {1..5}
do
   # Replace <JENKINS_JOB_NAME> with the actual name of your Jenkins job
   curl -X POST https://<JENKINS_SERVER>/job/<JENKINS_JOB_NAME>/build --user <JENKINS_USERNAME>:<JENKINS_API_TOKEN>
done
